name: MicTether
options:
  bundleIdPrefix: com.zimin
targets:
  MicTether:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    productName: "MicTether"
    sources: [MicTether]
    info:
      path: MicTether/Info.plist
      properties:
        LSUIElement: true
        CFBundleName: "MicTether"
        CFBundleDisplayName: "MicTether"
        CFBundleShortVersionString: "1.1"
        CFBundleVersion: "2"
        CFBundleIconFile: "AppIcon"
        LSApplicationCategoryType: "public.app-category.utilities"
    resources:
      - path: MicTether/Resources/AppIcon.icns
      - path: MicTether/PrivacyInfo.xcprivacy
    entitlements:
      path: MicTether/MicTether.entitlements
    settings:
      base:
        ENABLE_APP_SANDBOX: YES
        CODE_SIGN_IDENTITY: "-"
        ASSETCATALOG_COMPILER_APPICON_NAME: ""
